language: node_js
sudo: false
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
install:
  - cd ./picture-upload/apps/web-client && npm install
script:
  - cd ./picture-upload/apps/web-client && npm test