apiVersion: v1
kind: Service
metadata:
  labels:
    app: photo-filter
  name: photo-filter
spec:
  selector:
    app: photo-filter
  ports:
    - port: 3002
      protocol: TCP
      targetPort: 3002 
